apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
        - name: streamlit
          image: nikhlendrareddy/streamlit-app:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8501
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
          volumeMounts:
            - mountPath: "/app/data"
              name: streamlit-storage
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
      volumes:
        - name: streamlit-storage
          persistentVolumeClaim:
            claimName: streamlit-pvc
